version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt/certs:/etc/nginx/certs
      - ./letsencrypt/html:/tmp/letsencrypt
      - static_volume:/app/staticfiles  # Share volume with the web service
    depends_on:
      - web

  letsencrypt:
    restart: always
    image: vdhpieter/letsencrypt-webroot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt/certs:/etc/letsencrypt
      - ./letsencrypt/html:/tmp/letsencrypt
    environment:
      - DOMAINS=apogee.twc1.net
      - EMAIL=admin@apogee.twc1.net
      - WEBROOT_PATH=/tmp/letsencrypt
      - EXP_LIMIT=30
      - CHECK_FREQ=30
      - CHICKENEGG=1
      - STAGING=0

volumes:
  postgres_data:
  letsencrypt:
    external: true
  static_volume:  # Define the shared volume
