# Generated by Django 5.0 on 2023-12-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclee', models.CharField(choices=[('preparatoire', 'Préparatoire'), ('licence', 'Licence'), ('ingenieur', 'Ingénieur'), ('master', 'Master'), ('doctorat', 'Doctorat')], default='preparatoire', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DossierEtudiant',
            fields=[
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Cne', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('numero_tele', models.CharField(blank=True, max_length=15, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dernier_diplome_obtenu', models.CharField(blank=True, choices=[('deug', 'Deug'), ('deust', 'Deust'), ('deup', 'Deup'), ('dut', 'Dut')], max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, max_length=255, null=True)),
                ('Formation_souhaitée', models.CharField(blank=True, choices=[('deust', 'Deust'), ('licence', 'Licence'), ('cycle dingénieur', 'Cycle dingénieur'), ('master', 'Master')], max_length=30, null=True)),
                ('note_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_s3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_s4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_s5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_s6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('transcript', models.FileField(blank=True, null=True, upload_to='transcripts/')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ControleConnaissances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('règles_calcul', models.TextField()),
                ('coefficients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apogee_.coefficient')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionPédagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='apogee_.cycle')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='apogee_.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='coefficient',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apogee_.matiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apogee_.professeur'),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classement', models.IntegerField(blank=True, null=True)),
                ('moyennes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apogee_.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention_stage', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
