# Generated by Django 5.0 on 2023-12-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apogee_', '0002_remove_stage_convention_stage_stage_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='stage',
            name='convention_stage',
            field=models.TextField(default='Default Convention Stage'),
        ),
    ]
