# Generated by Django 5.0 on 2024-01-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apogee_', '0003_remove_stage_etudiant_stage_convention_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='adresse_d_entreprise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='periode_de_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
